capgoing/BE

src/main/java/com/going/server/domain/cluster/entity/Cluster.java, src/main/java/com/going/server/domain/cluster/repository/ClusterRepository.java, src/main/java/com/going/server/domain/cluster/service/ClusterServiceImpl.java, src/main/java/com/going/server/domain/sentence/entity/Sentence.java, src/main/java/com/going/server/domain/word/entity/Word.java, src/main/java/com/going/server/domain/word/repository/WordRepository.java
대표 어휘 조회 api에서 이미지 url을 받아오는 부분을 변경
=> ♻️ [Refactor] 대표 어휘 조회 api 변경 

.github/workflows/CI.yml, .github/workflows/CICD.yml, src/main/java/com/going/server/domain/ocr/OcrParser.java, src/main/java/com/going/server/domain/ocr/OcrService.java, src/main/java/com/going/server/domain/ocr/PdfOcrService.java, src/main/java/com/going/server/domain/upload/controller/UploadController.java, src/main/java/com/going/server/domain/upload/dto/UploadRequestDto.java, src/main/java/com/going/server/domain/upload/dto/UploadResponseDto.java, src/main/java/com/going/server/domain/upload/service/UploadService.java, src/main/java/com/going/server/domain/upload/service/UploadServiceImpl.java
- close #42 
- ocr 템플릿 등록
- 네이버 ocr api 호출 -> 텍스트 추출 진행
- responseDto, requestDto 생성 
어떤 변경 사항이 있나요?
PR이 다음 요구 사항을 충족하는지 확인하세요.
=> ✨[feat] pdf 업로드 및 ocr 텍스트 추출 기능 구현 

src/main/java/com/going/server/domain/cluster/controller/ClusterController.java, src/main/java/com/going/server/domain/graph/controller/graphController.java, src/main/java/com/going/server/domain/history/controller/HistoryController.java, src/main/java/com/going/server/domain/sentence/controller/SentenceController.java, src/main/java/com/going/server/domain/upload/controller/UploadController.java, src/main/java/com/going/server/domain/word/controller/WordController.java
- close #49 
스웨거에서 api를 그룹별로 나눠 프론트엔드 개발자가 보기 쉽게 함
PR이 다음 요구 사항을 충족하는지 확인하세요.
=> 📝[docs] 스웨거 api 그룹화를 위한 Tag 설정

src/main/java/com/going/server/global/config/SwaggerConfig.java
- close #54
- 프론트와의 통신이 가능하도록 스웨거 세팅을 수정했습니다.
- Nginx 리버스 프록시 설정을 한번 더 확인했습니다.
어떤 변경 사항이 있나요?
스웨거 세팅부분 수정
PR이 다음 요구 사항을 충족하는지 확인하세요.
=> 🛠 [config] Spring Boot - React 통신을 위한 CORS 및 Nginx 설정

src/main/java/com/going/server/domain/quiz/controller/QuizController.java, src/main/java/com/going/server/domain/quiz/dto/ConnectQuizDto.java, src/main/java/com/going/server/domain/quiz/dto/ListenUpQuizDto.java, src/main/java/com/going/server/domain/quiz/dto/PictureQuizDto.java, src/main/java/com/going/server/domain/quiz/dto/QuizCreateResponseDto.java, src/main/java/com/going/server/domain/quiz/dto/QuizListResponseDto.java, src/main/java/com/going/server/domain/quiz/service/QuizService.java, src/main/java/com/going/server/domain/quiz/service/QuizServiceImpl.java
- close #57 
listenUp모드 퀴즈 생성에 대한 API 세팅 및 로직 설계를 완료했습니다.
어떤 변경 사항이 있나요?
=> ✨  [feat] 퀴즈 생성 api 구조 셋팅 (listenUp 모드)

docker-compose.yml, src/main/java/com/going/server/domain/graph/entity/Graph.java, src/main/java/com/going/server/domain/graph/entity/GraphEdge.java, src/main/java/com/going/server/domain/graph/entity/GraphNode.java
- Close #62 
Graph 관련 Entity 생성 및 필요 메서드 생성, Neo4j APOC 플러그인 활성화
어떤 변경 사항이 있나요?
프론트와의 통신 시 Graph 관련 Entity의 getIdAsString() 사용해서 그래프 id를 String으로 가져오시면 됩니다.
=> ✨ [feat] 지식그래프 관련 Entity 생성 및 Mock Data 삽입

src/main/java/com/going/server/domain/graph/dto/NodeDto.java, src/main/java/com/going/server/domain/graph/repository/GraphRepository.java, src/main/java/com/going/server/domain/graph/service/GraphServiceImpl.java
- close #74 
- 지식그래프 상세 조회 로직 작성
- 지식그래프 삭제 로직 작성
어떤 변경 사항이 있나요?
=> ✨ [feat] 지식그래프 상세조회, 삭제 api 완성

src/main/java/com/going/server/domain/quiz/dto/PictureQuizDto.java, src/main/java/com/going/server/domain/quiz/exception/QuizErrorCode.java, src/main/java/com/going/server/domain/quiz/exception/QuizImageException.java, src/main/java/com/going/server/domain/quiz/exception/UnsupportedQuizModeException.java, src/main/java/com/going/server/domain/quiz/generate/ListenUpQuizGenerator.java, src/main/java/com/going/server/domain/quiz/generate/PictureQuizGenerator.java, src/main/java/com/going/server/domain/quiz/service/QuizServiceImpl.java
- close #69 
- Quiz 생성 관련 예외처리 로직 추가 - 지원하지 않는 mode (400)
- picture mode 생성 로직 구현 (S3, OpenAI 관련 로직 제외)
어떤 변경 사항이 있나요?
=> ✨ [feat] Picture Quiz 생성 로직 구현 API

src/main/java/com/going/server/domain/graph/controller/GraphController.java, src/main/java/com/going/server/domain/graph/dto/NodeAddDto.java, src/main/java/com/going/server/domain/graph/dto/NodeDto.java, src/main/java/com/going/server/domain/graph/entity/GraphNode.java, src/main/java/com/going/server/domain/graph/repository/GraphNodeRepository.java, src/main/java/com/going/server/domain/graph/service/GraphService.java, src/main/java/com/going/server/domain/graph/service/GraphServiceImpl.java, src/main/java/com/going/server/domain/upload/service/UploadServiceImpl.java
- close #79 
- 노드 삭제 로직 작성
- 노드 추가 로직 작성
- 
어떤 변경 사항이 있나요?
=> ✨ [feat] 노드 추가, 삭제 api 개발

.github/workflows/CICD.yml, Dockerfile
- close #93 
plain jar 제외하고 실행 가능한 jar만 업로드 및 복사하도록 수정
어떤 변경 사항이 있나요?
- 버그 수정
=> 🐛 [fix(ci)] : plain jar 제외하고 실행 가능한 jar만 업로드 및 복사하도록 수정

.github/workflows/CICD.yml, Dockerfile
- close #93
- develop 브랜치 push 시 prod 프로필로 빌드 및 배포되도록 수정.
- plain jar 파일 제외, 실행 가능한 jar만 복사하도록 수정.
어떤 변경 사항이 있나요?
- 버그 수정
=> 🐛 [fix(ci)] 브랜치 별 프로필 설정 및 bootJar 기반 배포 수정

.github/workflows/CICD.yml, Dockerfile, build.gradle
- close #93
DockerFile 수정
어떤 변경 사항이 있나요?
=> 🐛 [fix] DockerFile 수정

.github/workflows/CICD.yml, Dockerfile, build.gradle
- close #93 
GitHub Actions 빌드 스크립트에 중복된 bootJar 실행이 있어 수정 필요
- 'Clean and Build BootJar' 스텝만 유지하여 깔끔하게 정리
=> 🐛 [fix] CI build 중복 제거 및 clean bootJar로 통일

.github/workflows/CICD.yml, Dockerfile, build.gradle
- close #93
ci.yml 수정
어떤 변경 사항이 있나요?
=> 🐛 [fix] ci.yml 수정

.github/workflows/CICD.yml, Dockerfile, build.gradle
- close #93
cicd.yml 수정
어떤 변경 사항이 있나요?
- 버그 수정
=> 🐛 [fix] CICD.yml 수정

.github/workflows/CICD.yml, Dockerfile
CI/CD 파이프라인에서 JAR 파일의 존재 여부를 확인하고 docker 빌드가 올바른 파일을 사용하도록 하여
빌드 및 배포 과정에서 발생할 수 있는 오류를 방지하기 위해 작업함
- CI/CD 파이프라인에 `build/libs` 디렉토리의 내용 목록을 출력하여 `bootJar` 빌드 후 JAR 파일의 존재 여부를 확인하는 단계를 추가함
- Docker 빌드 전에 JAR 파일이 올바르게 생성되었는지 확인하는 단계를 추가함
- `JAR` 파일의 `MANIFEST.MF`에서 `Main-Class`가 올바르게 설정되었는지 체크하는 명령어를 추가함
- Docker 이미지 빌드 단계에서 올바른 JAR 파일을 참조하는지 확인하는 단계를 추가함
어떤 변경 사항이 있나요?
- 버그 수정
- 코드 리팩토링
=> 🐛 [fix(cicd)] CI/CD 파이프라인 수정 - buid/libs check , Docker build  전 JAR file 검증

.github/workflows/CICD.yml, Dockerfile
- close #93
CICD 파이프라인에 현재 실행중인 디렉토리 위치 출력 스텝 추가
어떤 변경 사항이 있나요?
-버그 수정
=> 🐛 [fix] CICD 파이프라인에 현재 실행중인 디렉토리 위치 출력 

.github/workflows/CICD.yml, Dockerfile
=> 🐛 [fix] CICD.yml 경로 수정

.github/workflows/CICD.yml, Dockerfile
- close #93
CICD, Dockerfile 수정
=> 🐛 [fix] CICD 수정

.github/workflows/CICD.yml, Dockerfile
- close #93
Dockerfile 및 CICD.yml 수정
어떤 변경 사항이 있나요?
- 버그 수정
=> 🐛 [fix] Dockerfile 및 CICD.yml 수정

.github/workflows/CICD.yml, Dockerfile, build.gradle
- close #93
Build.gradle 및 cicd.yml 수정
어떤 변경 사항이 있나요?
=> 🐛 [fix] build.gradle 및 cicd.yml 수정

.github/workflows/CICD.yml, Dockerfile, build.gradle
- close #93
Dockfile 및 CICD.yml 수정
어떤 변경 사항이 있나요?
- 버그 수정
=> 🐛 [fix] Dockfile 및 CICD.yml 수정

.github/workflows/CICD.yml, Dockerfile, build.gradle, docker-compose.yml
- close #93
Dockerfile, gradle, cicd.yml 수정
어떤 변경 사항이 있나요?
=> 🐛 [fix] Dockerfile, gradle, cicd.yml 수정

.github/workflows/CICD.yml, Dockerfile, build.gradle, docker-compose.yml
=> 🐛 [fix] Spring Boot 애플리케이션 실행 구조 개선

.github/workflows/CICD.yml, build.gradle
=> 🐛 [fix] build.gradle 수정

.github/workflows/CICD.yml, Dockerfile, build.gradle
=> 🐛 [fix] 파이프라인 및 gradle 수정

.github/workflows/CI.yml, build.gradle, src/main/java/com/going/server/domain/graph/dto/NodeDto.java, src/main/java/com/going/server/domain/graph/entity/GraphNode.java, src/main/java/com/going/server/domain/graph/service/GraphServiceImpl.java, src/main/java/com/going/server/domain/quiz/generate/ConnectQuizGenerator.java, src/main/java/com/going/server/domain/upload/service/UploadServiceImpl.java, src/test/java/com/going/server/ServerApplicationTests.java
- close #119 
-  노드 라벨에 맞는 이미지를 보여주기 위해 unsplash api를 통신하였습니다.
어떤 변경 사항이 있나요?
=> ✨ [feat] Unsplash Api 통신

build.gradle, src/main/java/com/going/server/ServerApplication.java, src/main/java/com/going/server/global/common/ExceptionDiscordLoggingAspect.java, src/main/java/com/going/server/global/common/LogAspect.java, src/main/java/com/going/server/global/common/SkipNotification.java, src/main/java/com/going/server/global/common/TraceFileResource.java
- close #55 
컨트롤러 및 서비스 계층에 AOP 적용
서비스 메서드 실행 시간 로그 출력
컨트롤러 요청 파라미터 및 URI 로깅
예외 발생 시 디스코드 Webhook 으로 에러 메시지 전송
어떤 변경 사항이 있나요?
=> ✨[feat]  AOP 기반 실행 로그 및 에러 알림 기능 추가

src/main/java/com/going/server/domain/upload/service/UploadServiceImpl.java
=> 🚧 OCR SLF4J log 코드 복구

src/main/java/com/going/server/domain/openai/service/RAGAnswerCreateService.java
- #176 
RAG 챗봇 응답 temperature 낮춤
어떤 변경 사항이 있나요?
=> ⚡️ [perf] RAG 챗봇 응답 temperature 낮춤

src/main/java/com/going/server/domain/openai/service/TextSummaryCreateService.java
- #176 
마크다운 문법 적용범위 수정에 따른 프롬프트 수정
어떤 변경 사항이 있나요?
=> ✏️ [fix] 마크다운 문법 적용범위  수정에 따른 프롬프트 수정

src/main/java/com/going/server/domain/openai/service/RAGAnswerCreateService.java
4o -> o1-priview
- #176 
openAI API 모델 변경
어떤 변경 사항이 있나요?
o1-priview는 매우 비싼 모델이기 때문에 너무 많은 요청은 자제해야 함.
=> ⚡️ Perf: openAI API 모델 변경

src/main/java/com/going/server/domain/openai/service/RAGAnswerCreateService.java
- #176 
RAG 성능 개선 진행 중
성능 확인을 위한 배포
어떤 변경 사항이 있나요?
=> 🚧 Progress: RAG 성능 개선 진행 중

src/main/java/com/going/server/domain/openai/service/RAGAnswerCreateService.java
=> ✏️ Fix: RAG Request에 채팅 목록 추가 제거

src/main/java/com/going/server/domain/graph/service/GraphServiceImpl.java
graph dbId 추가로 인해 발생한 지식그래프 삭제 관련 오류 해결
어떤 변경 사항이 있나요?
=> 🐛 [fix] graph dbId 추가로 인해 발생한 지식그래프 삭제 관련 오류 해결

src/main/java/com/going/server/domain/quiz/generate/PictureQuizGenerator.java
프론트 요청에 따른 이미지 퀴즈 사이즈 수정
어떤 변경 사항이 있나요?
=> ♻️ [Refactor] 퀴즈 이미지 생성 사이즈 수정
